FEAT: Increase size of HTML Editor
django-cms/djangocms-snippet pull request #112
Opened 2022-04-02 15:47 UTC by crydotsnake

## Description

This pull request increases the size of the HTML Editor a bit.

#### Before

![Bildschirmfoto 2022-04-02 um 17 39 15](https://user-images.githubusercontent.com/39345336/161390745-16842c9c-9ba6-45ef-a961-580f749658b1.png)

#### After

![Bildschirmfoto 2022-04-02 um 17 39 48](https://user-images.githubusercontent.com/39345336/161390749-96b9a695-1eb5-4e6a-9390-0683412c0514.png)

The size of the editor wasnt changing automatically, if you added a snippet into it

* [x] I have opened this pull request against ``master``
* [ ] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2022-05-30 10:32 UTC, fsbraun reviewed
HI @crydotsnake ! 

I've tried to take the dark mode somewhat further. Maybe you can already incorporate this here?

Thanks so much!

2022-05-30 10:32 UTC, fsbraun commented on djangocms_snippet/templates/djangocms_snippet/admin/change_form.html
> +    if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
@crydotsnake I've "played" with dark mode some more and now am proposing a global toggle in the cms toolbar (see https://github.com/django-cms/django-cms/pull/7329). Can I propose to update this media query as follows:


            var darkMode;
            if (window.parent.CMS.API.Toolbar.get_color_scheme) {
                darkMode = window.parent.CMS.API.Toolbar.get_color_scheme() === 'dark';
            } else {
                // django CMS pre-3.11
                darkMode =  window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
            }
            if (darkMode) {
                editor.setTheme('ace/theme/tomorrow_night');
            }  else {
                editor.setTheme('ace/theme/github');
            }

2022-06-19 12:44 UTC, marksweb requested changes
There's outstanding change requests here without the completed review to flag these.

2022-06-19 19:16 UTC, fsbraun requested changes
Hi @crydotsnake ! I‘ve added some comments to adjust to the improved dark mode feature. Would you mind looking at them?

2023-02-10 12:03 UTC, closed without merging