Fix: Removed autoescape from preview template, tags will now be rendered
django-cms/djangocms-snippet pull request #96
Opened 2022-01-04 12:04 UTC by adam-murray

## Description

## Related resources

* #...
* #...

## Checklist

* [ ] I have opened this pull request against ``master``
* [ ] I have added or modified the tests when changing logic
* [ ] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2022-01-04 12:40 UTC, marktsavage approved these changes

2022-01-05 16:27 UTC, Bernardvdv approved these changes

2022-01-05 16:46 UTC, Aiky30 requested changes
1. Missing a changelog entry

2. The PR description needs to be updated, a lot of unpopulated template exists.

2022-01-07 10:38 UTC, Aiky30 approved these changes

2022-02-11 16:40 UTC, Aiky30 requested changes
Minor change to the text in the changelog.

2022-02-11 16:40 UTC, Aiky30 commented on CHANGELOG.rst
> +* fix: Added test coverage to admnin preview button
```suggestion
* fix: Added test coverage to admin preview view
```

2022-02-14 10:22 UTC, merged