Removing slug field from list display when versioning is enabled
django-cms/djangocms-snippet pull request #98
Opened 2022-01-05 13:45 UTC by Bernardvdv

## Description

## Related resources

* #...
* #...

## Checklist

* [ ] I have opened this pull request against ``master``
* [ ] I have added or modified the tests when changing logic
* [ ] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2022-01-05 14:24 UTC, adam-murray commented on djangocms_snippet/admin.py
> +        if not djangocms_versioning_enabled:
Same as above

2022-01-05 14:24 UTC, adam-murray commented on djangocms_snippet/admin.py
> +            prepopulated_fields = {'slug': ('name',)}
Same as above

2022-01-05 14:42 UTC, Aiky30 commented on djangocms_snippet/admin.py
> +        if not djangocms_versioning_enabled:
If that is the case in the except we can nullify djangocms_versioning_enabled.

```
try:
    from djangocms_versioning.admin import ExtendedVersionAdminMixin
    if djangocms_versioning_enabled:
        snippet_admin_classes.insert(0, ExtendedVersionAdminMixin)
except ImportError:
    djangocms_versioning_enabled = False
```

2022-01-05 16:03 UTC, Aiky30 approved these changes

2022-01-05 16:21 UTC, adam-murray approved these changes

2022-01-05 16:48 UTC, Aiky30 requested changes
This will fail Kuldeeps requirements, the name is now the link to the field. The reason Kuldeep wanted the slug removed was due to the fact that it was linked to. The link needs to be removed, this is done by the versioning controls.

2022-01-06 14:54 UTC, adam-murray approved these changes

2022-01-06 14:58 UTC, marktsavage approved these changes

2022-01-07 10:29 UTC, Aiky30 requested changes
Sorry for this but as we have a business requirement for this behaviour we will have to protect it with tests. :-(

2022-01-10 17:36 UTC, Aiky30 approved these changes

2022-01-10 17:36 UTC, merged